# Generated by Django 3.2.9 on 2022-01-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='./images/default_image.png', upload_to='./images/categories'),
        ),
    ]
