# Generated by Django 3.2.9 on 2022-01-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='./images/default_image.png', upload_to='./images/'),
        ),
    ]
