# Generated by Django 3.2.9 on 2022-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='./images/default_image.png', upload_to='./images'),
        ),
    ]
